apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../metrics
  - ingress.yaml
configMapGenerator:
  - name: metrics-env
    behavior: merge
    literals:
      - NEXTCLOUD_SERVER="http://nextcloud.nextcloud.svc:8080"
secretGenerator:
  # Don't put raw secrets in your source code. Use ksops instead
  - name:  metrics-env
    literals:
      - NEXTCLOUD_USER=change-me
      - NEXTCLOUD_PASSWORD=change-me
  - name: env
    literals:
      - NEXTCLOUD_ADMIN_USER=change-me-admin
      - NEXTCLOUD_ADMIN_PASSWORD=change-me-admin
